name: Build and Deploy

on:
  push:
    branches:
      - main # Change this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Start server
        run: |
          npm install -g serve
          serve -s build -l 3000 > /dev/null 2>&1 &

      - name: Open in browser
        run: |
          sleep 3
          xdg-open http://localhost:3000
